development:
  adapter: postgresql
  database: Blogger_App
  username: gisha
  password: qburst
  encoding: unicode
  host: localhost
  pool: 5
test:
  adapter: postgresql
  database: Blogger_App
  username: gisha
  password: qburst
  encoding: unicode
  host: localhost
  pool: 5
